force-app/main/default/objects/BSC_Question__c/BSC_Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BSC_Question__c/fields/Is_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BSC_Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSC_Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
                <isActive>false</isActive>
                <label>Calculated</label>
            </value>
            <value>
                <fullName>Yes/No</fullName>
                <isActive>false</isActive>
                <label>Yes/No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BSC_Question__c/fields/Risk_Assessment_Section__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Section__c</fullName>
    <label>Risk Assessment Section</label>
    <referenceTo>BSC_Risk_Assessment_Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BSC_Question__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Used only if question type is List. The weight will be multiplied with the option score to define the final score for an answer.</description>
    <label>Weight</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BSC_Question_Option__c/BSC_Question_Option__c.object-meta.xml
<CustomObject>
    <label>Question Option</label>
    <nameField>
        <label>Question Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BSC_Question_Option__c/fields/Option_Score__c.field-meta.xml
<CustomField>
    <fullName>Option_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is multiplied with question&#39;s weight to define the final score for the question</description>
    <label>Option Score</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BSC_Question_Option__c/fields/Option_Value__c.field-meta.xml
<CustomField>
    <fullName>Option_Value__c</fullName>
    <label>Option Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSC_Question_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>BSC_Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Assessment_Definition__c/BSC_Risk_Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Risk Assessment  Definition</label>
    <nameField>
        <label>Risk Assessment  Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessment  Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BSC_Risk_Assessment_Definition__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Assessment_Definition__c/fields/Initial_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Initial Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Assessment_Section__c/BSC_Risk_Assessment_Section__c.object-meta.xml
<CustomObject>
    <label>Risk Assessment Section</label>
    <nameField>
        <label>Risk Assessment Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessment Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BSC_Risk_Assessment_Section__c/fields/DisplayText__c.field-meta.xml
<CustomField>
    <fullName>DisplayText__c</fullName>
    <label>DisplayText</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Assessment_Section__c/fields/Risk_Assessment_Definition__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Definition__c</fullName>
    <label>Risk Assessment  Definition</label>
    <referenceTo>BSC_Risk_Assessment_Definition__c</referenceTo>
    <relationshipLabel>Risk Assessment Section</relationshipLabel>
    <relationshipName>Risk_Assessment_Section</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Assessment_Section__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Category__c/BSC_Risk_Category__c.object-meta.xml
<CustomObject>
    <label>Risk Category</label>
    <nameField>
        <label>Risk Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BSC_Risk_Category__c/fields/Case_Priority__c.field-meta.xml
<CustomField>
    <fullName>Case_Priority__c</fullName>
    <description>To be mapped with the case priority - if needs to be created</description>
    <label>Case Priority</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Category__c/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <description>Developer Name for the case record type to be created</description>
    <label>Case Record Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Category__c/fields/Create_a_Case__c.field-meta.xml
<CustomField>
    <fullName>Create_a_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create a Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Category__c/fields/Final_Message_To_Display__c.field-meta.xml
<CustomField>
    <fullName>Final_Message_To_Display__c</fullName>
    <label>Final Message To Display</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Category__c/fields/Minimum_Score__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Score__c</fullName>
    <label>Minimum Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BSC_Risk_Category__c/fields/Risk_Assessment_Definition__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Definition__c</fullName>
    <label>Risk Assessment  Definition</label>
    <referenceTo>BSC_Risk_Assessment_Definition__c</referenceTo>
    <relationshipLabel>Risk Categories</relationshipLabel>
    <relationshipName>Risk_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
            <value>
                <fullName>Yes/No</fullName>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Risk_Assessment_Section__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Section__c</fullName>
    <label>Risk Assessment Section</label>
    <referenceTo>Risk_Assessment_Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Weight</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Risk_Assessment_Definition__c/Risk_Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Risk Assessment  Definition</label>
    <nameField>
        <label>Risk Assessment  Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessment  Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Assessment_Definition__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Risk_Assessment_Definition__c/fields/Initial_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Initial Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Risk_Assessment_Section__c/Risk_Assessment_Section__c.object-meta.xml
<CustomObject>
    <label>Risk Assessment Section</label>
    <nameField>
        <label>Risk Assessment Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessment Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Assessment_Section__c/fields/Risk_Assessment_Definition__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Definition__c</fullName>
    <label>Risk Assessment  Definition</label>
    <referenceTo>Risk_Assessment_Definition__c</referenceTo>
    <relationshipLabel>Risk Assessment Section</relationshipLabel>
    <relationshipName>Risk_Assessment_Section</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RiskAssessmentFlowControllerTest.cls
@isTest()
public with sharing class RiskAssessmentFlowControllerTest {
    @TestSetup
    static void makeData() {
        BSC_Risk_Assessment_Definition__c def = new BSC_Risk_Assessment_Definition__c(
            Name = 'TestForm',     
            Active__c = true,
            Initial_Date__c = Date.Today());
        
        insert def;

        BSC_Risk_Assessment_Section__c section = new BSC_Risk_Assessment_Section__c(
            Risk_Assessment_Definition__c = def.Id,
            DisplayText__c = 'Sintomas',
            Name = 'Sintomas',
            Sequence__c = 10
        );
        insert section;

        BSC_Question__c question = new BSC_Question__c(
            Name = 'Febre (acima de 37,8)?',
            Question_Text__c = 'Está com febre (acima de 37,8˚)?',
            Question_Type__c = 'List',
            Sequence__c = 10,
            Weight__c = 1,
            Is_Required__c = true,
            Risk_Assessment_Section__c = section.Id
        );
        insert question;

        BSC_Question_Option__c option = new BSC_Question_Option__c(
            Name = 'Sim',
            Option_Score__c = 10,
            Option_Value__c = 'Sim', 
            Question__c = question.Id
        );
        insert option;

        option = new BSC_Question_Option__c(
            Name = 'Não',
            Option_Score__c = 0,
            Option_Value__c = 'Não', 
            Question__c = question.Id
        );
        insert option;

        BSC_Risk_Category__c category = new BSC_Risk_Category__c(
            Case_Record_Type__c = 'Base',
            Final_Message_To_Display__c = 'Mantenha-se em isolamento relativo em casa, meça temperature 4 x ao dia e repita a auto-avaliação de 2 em 2 dias.',
            Minimum_Score__c = 10,
            Name = 'Paciente de Médio Risco',
            Risk_Assessment_Definition__c = def.Id,
            Create_a_Case__c = true, 
            Case_Priority__c = 'Medium'
        );
        insert category;

    }

    @IsTest
    static void testGetRiskAssessmentQuestionaire(){
        Test.startTest();
        List<RiskAssessmentFlowController.Section> secoes = RiskAssessmentFlowController.getRiskAssessmentQuestionaire('TestForm');
        System.assertEquals(secoes.size(), 1);
        System.assertEquals(secoes.get(0).questions.get(0).options.size(), 2);
        Test.stopTest();
    }

    @IsTest
    static void testGetRiskAssessmentCategory() {
        Test.startTest();
        RiskAssessmentFlowController.Category cat = RiskAssessmentFlowController.getRiskAssessmentCategory('TestForm', 10, null);
        System.assert(cat.createACase);
        cat = RiskAssessmentFlowController.getRiskAssessmentCategory('TestForm', 9, null);
        System.assertEquals(cat, null);
        Test.stopTest();
    }

    @IsTest
    static void testCreateOrUpdateCase() {
        Test.startTest();
        RiskAssessmentFlowController.Category cat = RiskAssessmentFlowController.getRiskAssessmentCategory('TestForm', 10, null);
        
        RiskAssessmentFlowController.CreateCaseRequest request = new RiskAssessmentFlowController.CreateCaseRequest();
        request.riskCategoryId = cat.categoryId;
        request.respostas = 'Respostas';
        request.nomeContato = 'Teste';
        request.email = 'teste@teste.com';
        request.phone = '11-99111-9911';
        
        String idCaso = RiskAssessmentFlowController.createUpdateCase(request);
        System.assertNotEquals(idCaso, null);
        Case caso = [SELECT Id FROM Case WHERE Id = :idCaso];
        System.assert(caso != null);
        Test.stopTest();
    }

}