force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
            <value>
                <fullName>Yes/No</fullName>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Risk_Assessment_Section__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Section__c</fullName>
    <label>Risk Assessment Section</label>
    <referenceTo>Risk_Assessment_Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Weight</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
<CustomObject>
    <label>Question Option</label>
    <nameField>
        <label>Question Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Option__c/fields/Option_Score__c.field-meta.xml
<CustomField>
    <fullName>Option_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Option Score</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Option__c/fields/Option_Value__c.field-meta.xml
<CustomField>
    <fullName>Option_Value__c</fullName>
    <label>Option Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Assessment_Definition__c/Risk_Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Risk Assessment  Definition</label>
    <nameField>
        <label>Risk Assessment  Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessment  Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Assessment_Definition__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Risk_Assessment_Definition__c/fields/Initial_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Initial Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Risk_Assessment_Section__c/Risk_Assessment_Section__c.object-meta.xml
<CustomObject>
    <label>Risk Assessment Section</label>
    <nameField>
        <label>Risk Assessment Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessment Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Assessment_Section__c/fields/Risk_Assessment_Definition__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Definition__c</fullName>
    <label>Risk Assessment  Definition</label>
    <referenceTo>Risk_Assessment_Definition__c</referenceTo>
    <relationshipLabel>Risk Assessment Section</relationshipLabel>
    <relationshipName>Risk_Assessment_Section</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RiskAssessmentFlowController.cls
public with sharing class RiskAssessmentFlowController {

    @AuraEnabled(cacheable=true)
    public static List<Section> getRiskAssessmentQuestionaire() {

        List<Section> sectionList = new List<Section>();

        Risk_Assessment_Definition__c rad = 
            [SELECT Id
            FROM Risk_Assessment_Definition__c WHERE Active__c = TRUE 
            ORDER BY Initial_Date__c DESC  
            LIMIT 1];

        List<Risk_Assessment_Section__c> sectionsc = 
            [SELECT Id, Name From Risk_Assessment_Section__c 
            WHERE Risk_Assessment_Definition__c = :rad.Id 
            ORDER BY Sequence__c];

        for (Risk_Assessment_Section__c sectionc : sectionsc) {
            Section sec = new Section();
            sec.Id = sectionc.Id;
            sec.text = sectionc.Name;
            sec.questions = new List<Question>();

            List<Question__c> questionsc = 
                [SELECT Id, Question_Text__c, Question_Type__c, Weight__c, 
                    (Select Id, Option_Value__c, Option_Score__c FROM Question_Options__r) 
                FROM Question__c 
                WHERE Risk_Assessment_Section__c = :sectionc.Id
                ORDER BY Sequence__c];

            for (Question__c questionc : questionsc) {
                Question qst = new Question();
                qst.id = questionc.Id;
                qst.text = questionc.Question_Text__c;
                qst.setType(questionc.Question_Type__c);
                qst.weight = questionc.Weight__c;
                qst.options = new List<Option>();
                if (questionc.Question_Options__r != null && questionc.Question_Options__r.size() > 0) {
                    for (Question_Option__c optionc : questionc.Question_Options__r) {
                        Option opt = new Option();
                        opt.label = optionc.Option_Value__c;
                        opt.value = String.valueOf(optionc.Option_Score__c);
                        qst.options.add(opt);
                    }
                }
                sec.questions.add(qst);
            }
            sectionList.add(sec);
        }

        System.debug('Quantity of sections found: ' + sectionList.size());
        for (Section sec : sectionList) {
            System.debug('Section: ' + JSON.serializePretty(sec));
        }

        return sectionList;
    }

    public class Option {
        @AuraEnabled public String label;
        @AuraEnabled public String value;
    }

    public class Question {
        @AuraEnabled public Id id; 
        @AuraEnabled public String text;
        @AuraEnabled public String type;
        @AuraEnabled public Double weight;
        @AuraEnabled public List<Option> options;
        @AuraEnabled public Boolean isText;
        @AuraEnabled public Boolean isNumber;
        @AuraEnabled public Boolean isYesNo;
        @AuraEnabled public Boolean isList;
    

        public void setType(String type) {
            this.type = type;
            this.isText = 'Text'.equals(type);
            this.isNumber = 'Number'.equals(type);
            this.isYesNo = 'Yes/No'.equals(type);
            this.isList = 'List'.equals(type);
        }
    }
    
    public class Section {
        @AuraEnabled public Id id;
        @AuraEnabled public String text;
        @AuraEnabled public List<Question> questions;
    }
    
    public class Category {
        @AuraEnabled public double minimumScore;
        @AuraEnabled public String textToDisplay;
    }
    
}